# # Starter pipeline
# # Start with a minimal pipeline that you can customize to build and deploy your code.
# # Add steps that build, run tests, deploy, and more:
# # https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Npm@1
  inputs:
    command: 'install'
  env:
    SESSION_SECRET: $(SESSION_SECRET)
    DB_URI: $(DB_URI)
    STRIPE_SECRET: $(STRIPE_SECRET)

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run webpack'
  env:
    SESSION_SECRET: $(SESSION_SECRET)
    DB_URI: $(DB_URI)
    STRIPE_SECRET: $(STRIPE_SECRET)

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'test'
  env:
    SESSION_SECRET: $(SESSION_SECRET)
    DB_URI: $(DB_URI)
    STRIPE_SECRET: $(STRIPE_SECRET)

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: 'send the build off to release'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  env:
    SESSION_SECRET: $(SESSION_SECRET)
    DB_URI: $(DB_URI)
    STRIPE_SECRET: $(STRIPE_SECRET)
